server:
  port: 8082

spring:
  #邮件配置
  mail:
    #邮件服务器地址
    host: smtp.qq.com
    #协议
    protocol: smtp
    #编码格式
    default-encoding: UTF-8
    #授权码
    password: oarkswheepudcjcc
    #发送者邮箱地址
    username: 3293971399@qq.com
    #SMTP端口
    port: 25

  #rabbitmq配置
  rabbitmq:
    #用户名
    username: guest
    #密码
    password: guest
    #服务器地址
    host: localhost
    #端口
    port: 5672
    listener:
      simple:
        #开启手动确认
        acknowledge-mode: manual

  redis:
    #    超时时间
    timeout: 10000ms
    #    服务器地址
    host: localhost
    #    host: 192.168.10.100
    #    服务器端口
    port: 6379
    #    数据库
    database: 0
    #    密码
    #    password: root
    lettuce:
      pool:
        #        最大连接数，默认8
        max-active: 1024
        #        最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #        最大空闲连接
        max-idle: 200
        #        最小空闲连接
        min-idle: 5
